### ISSUE TITLE
消息格式修改，任务粒度支持到Second级别

### ISSUE THREAD

**Issue by yuanl2** [yuanl2/hsbackend#45]

**Comment by rainbowbird** [comment]
好改吗？

**Comment by yuanl2** [comment]
修改下发任务的消息格式
Old Msg:
 TRVBP,02,021,135,00,100,1,15,064,# 

New Msg:
TRVBP,02,021,135,00,100,1,15,00,064,#

15,00
15表示分钟，00表示秒
针对设备都额外多下发10秒，保证用户体验

由于Consume类型保存的task时间，是分钟力度，相应流程需要重新修改，保持秒级别
